# https://0xerr0r.github.io/blocky/latest/configuration
upstreams:
  init:
    # Blocky starts serving DNS immediately and initialization happens in the
    #  background. The feature requiring initialization will enable later on
    #  (if it succeeds).
    strategy: fast
  groups:
    default:
      # Cloudflare (DNS over HTTPS)
      - https://cloudflare-dns.com/dns-query
      # Mullvad (DNS over HTTPS)
      - https://dns.mullvad.net/dns-query

customDNS:
  mapping:
    orangepebble.net: 192.168.1.4

blocking:
  denylists:
    default:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/pro.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/domains/tif.txt
  clientGroupsBlock:
    default:
      - default

ports:
  dns: 53
  http: 4000
